//  PrivateURLs.java
//
//  `bundle install`
//  `./appkeeper.sh yonghui`
//
//  Created by lijunjie on 16/06/02.
//  Copyright © 2016年 com.intfocus. All rights reserved.
//

// current app: [yonghui]
// automatic generated by app_keeper.rb at 16/08/02 10:55
package com.intfocus.yh_android.util;

public class PrivateURLs {
  public final static String kBaseUrl      = "http://yonghui.idata.mobi";
  public final static String kBaseUrl1     = "http://10.0.3.2:4567";

  public final static String kPgyerAppId   = "c586f556015342bcf89f8300ccfbebc2";
  public final static String kPgyerUrl     = "http://www.pgyer.com/yh-a";
  
  public final static String kUMAppId      = "570f5750e0f55a54670017e1";
  public final static String kWXAppId      = "wx50edd59f119da198";
  public final static String kWXAppSecret  = "e8fa301d58ff838b93268eb0e6b14ccb";

  public final static boolean kDashboardTabBarDisplay        = true;
  public final static boolean kDashboardTabBarDisplayKPI     = true;
  public final static boolean kDashboardTabBarDisplayAnalyse = true;
  public final static boolean kDashboardTabBarDisplayApp     = true;
  public final static boolean kDashboardTabBarDisplayMessage = true;
  public final static boolean kDashboardDisplayScanCode      = true;
  public final static boolean kSubjectDisplayComment         = true;
  public final static boolean kSubjectDisplayShare           = false;
}
