//  PrivateURLs.java
//
//  `bundle install`
//  `./appkeeper.sh yonghui`
//
//  Created by lijunjie on 16/06/02.
//  Copyright © 2016年 com.intfocus. All rights reserved.
//

// current app: [yonghui]
// automatic generated by app_keeper.rb
package com.intfocus.yh_android.util;

public class PrivateURLs {
  public final static String kAppCode         = "yonghui";
  public final static String kThemeColor      = "#53a93f";
  public final static String kBannerBgColor   = "#53a93f";
  public final static String kBannerTextColor = "#ffffff";
  public final static String kInitPassword    = "123456";
  
  public final static String kBaseUrl      = "http://yonghui.idata.mobi";
  public final static String kBaseUrl1     = "http://10.0.3.2:4567";

  public final static String kPgyerAppId   = "c586f556015342bcf89f8300ccfbebc2";
  public final static String kPgyerUrl     = "http://www.pgyer.com/yh-a";
  
  public final static String kUMAppId      = "570f5750e0f55a54670017e1";
  public final static String kWXAppId      = "wx50edd59f119da198";
  public final static String kWXAppSecret  = "e8fa301d58ff838b93268eb0e6b14ccb";

  public final static boolean kDashboardAd      = false;
  public final static boolean kDropMenuScan     = true;
  public final static boolean kDropMenuSearch   = true;
  public final static boolean kDropMenuVoice    = true;
  public final static boolean kDropMenuUserInfo = true;
  
  public final static boolean kTabBar        = true;
  public final static boolean kTabBarKPI     = true;
  public final static boolean kTabBarAnalyse = true;
  public final static boolean kTabBarApp     = true;
  public final static boolean kTabBarMessage = true;
  
  public final static boolean kSubjectComment = true;
  public final static boolean kSubjectShare   = true;
}
